import type { Metadata } from "next";
import "./globals.css";
import { Space_Mono } from 'next/font/google'

const font = Space_Mono({ subsets: ["latin"], weight:"400",})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${font.className } antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
